services:
  web_interface:
    build:
      context: .
      dockerfile: web_interface/Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./persistent_storage/pdf_shipping_labels:/app/shipping/canada_post/cp_shipping/cp_pdf_shipping_labels
      - ./persistent_storage/logs:/app/logs
    depends_on:
      - postgres-db
      - redis
    environment:
      POSTGRES_HOST: postgres-db
      REDIS_HOST: redis

  postgres-db:
    image: postgres:13
    container_name: order_management_db
    mem_limit: 512m
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_cache
    mem_limit: 256m
    ports:
      - "6379:6379"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    mem_limit: 512m
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - postgres-db
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  pgadmin_data:
  grafana_data:


