version: '3.8'
services:
  web:
    build: ./web_interface
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./persistent_storage/pdf_shipping_labels:/app/shipping/canada_post/cp_shipping/cp_pdf_shipping_labels
      - ./persistent_storage/logs:/app/logs
    depends_on:
      - postgres-db
    environment:
      POSTGRES_HOST: postgres-db
  postgres-db:
    image: postgres:13
    container_name: order_management_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
